<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Version>2.12.2</Version>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Http" />
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
        <PackageReference Include="MessagePipe" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\VRChatContentPublisher.BundleProcessCore\VRChatContentPublisher.BundleProcessCore.csproj" />
        <ProjectReference Include="..\VRChatContentPublisher.ConnectCore\VRChatContentPublisher.ConnectCore.csproj" />
        <ProjectReference Include="..\VRChatContentPublisher.Core.Shared\VRChatContentPublisher.Core.Shared.csproj" />
        <ProjectReference Include="..\VRChatContentPublisher.SqliteCore\VRChatContentPublisher.SqliteCore.csproj" />
        <ProjectReference Include="..\VRChatContentPublisher.VRChatApi\VRChatContentPublisher.VRChatApi.csproj" />
    </ItemGroup>

    <Import Project="../../BuildInfo.targets" />
</Project>
