//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRChatContentPublisher.App.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VRChatContentPublisher.App.Localization.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        internal static string Common_Content_Type_Avatar {
            get {
                return ResourceManager.GetString("Common_Content_Type_Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        internal static string Common_Content_Type_World {
            get {
                return ResourceManager.GetString("Common_Content_Type_World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Update.
        /// </summary>
        internal static string Common_Views_Update_Progress_View_Cancel_Update_Button_Tooltip {
            get {
                return ResourceManager.GetString("Common_Views_Update_Progress_View_Cancel_Update_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Update....
        /// </summary>
        internal static string Common_Views_Update_Progress_View_Downloading_Update {
            get {
                return ResourceManager.GetString("Common_Views_Update_Progress_View_Downloading_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Common_Views_Update_Progress_View_Install_Update_Button {
            get {
                return ResourceManager.GetString("Common_Views_Update_Progress_View_Install_Update_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncompleted publish tasks exist.
        /// </summary>
        internal static string Common_Views_Update_Progress_View_Install_Update_Disabled_Due_To_Uncompleted_Tasks {
            get {
                return ResourceManager.GetString(("Common_Views_Update_Progress_View_Install_Update_Disabled_Due_To_Uncompleted_Task" +
                        "s"), resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update are ready to install.
        /// </summary>
        internal static string Common_Views_Update_Progress_View_Ready_To_Install_Title {
            get {
                return ResourceManager.GetString("Common_Views_Update_Progress_View_Ready_To_Install_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download update.
        /// </summary>
        internal static string Common_Views_Update_Progress_View_Update_Download_Failed_Title {
            get {
                return ResourceManager.GetString("Common_Views_Update_Progress_View_Update_Download_Failed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install update.
        /// </summary>
        internal static string Common_Views_Update_Progress_View_Update_Install_Failed_Title {
            get {
                return ResourceManager.GetString("Common_Views_Update_Progress_View_Update_Install_Failed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Common_Views_Update_Progress_View_Update_Retry_Download_Button_Tooltip {
            get {
                return ResourceManager.GetString("Common_Views_Update_Progress_View_Update_Retry_Download_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s News in v{0}.
        /// </summary>
        internal static string Common_Views_Update_Progress_View_What_News_Text_Template {
            get {
                return ResourceManager.GetString("Common_Views_Update_Progress_View_What_News_Text_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Cookie.
        /// </summary>
        internal static string Dialog_Login_Using_Cookies_Add_Cookie_Button_Text {
            get {
                return ResourceManager.GetString("Dialog_Login_Using_Cookies_Add_Cookie_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure you know what you are doing before using this feature..
        /// </summary>
        internal static string Dialog_Login_Using_Cookies_Alert_For_Advanced_Users_Only_Description {
            get {
                return ResourceManager.GetString("Dialog_Login_Using_Cookies_Alert_For_Advanced_Users_Only_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature are only for advanced users.
        /// </summary>
        internal static string Dialog_Login_Using_Cookies_Alert_For_Advanced_Users_Only_Title {
            get {
                return ResourceManager.GetString("Dialog_Login_Using_Cookies_Alert_For_Advanced_Users_Only_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will only apply for &quot;api.vrchat.cloud&quot;..
        /// </summary>
        internal static string Dialog_Login_Using_Cookies_Alert_Require_Cookies_Description {
            get {
                return ResourceManager.GetString("Dialog_Login_Using_Cookies_Alert_Require_Cookies_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies Required.
        /// </summary>
        internal static string Dialog_Login_Using_Cookies_Alert_Require_Cookies_Title {
            get {
                return ResourceManager.GetString("Dialog_Login_Using_Cookies_Alert_Require_Cookies_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Dialog_Login_Using_Cookies_Cancel_Button_Text {
            get {
                return ResourceManager.GetString("Dialog_Login_Using_Cookies_Cancel_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Dialog_Login_Using_Cookies_Cookie_Item_Clear_Value_Button_Tooltip {
            get {
                return ResourceManager.GetString("Dialog_Login_Using_Cookies_Cookie_Item_Clear_Value_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Dialog_Login_Using_Cookies_Cookie_Item_Name_Field_Hint {
            get {
                return ResourceManager.GetString("Dialog_Login_Using_Cookies_Cookie_Item_Name_Field_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Dialog_Login_Using_Cookies_Cookie_Item_Paste_Button_Tooltip {
            get {
                return ResourceManager.GetString("Dialog_Login_Using_Cookies_Cookie_Item_Paste_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Cookie.
        /// </summary>
        internal static string Dialog_Login_Using_Cookies_Cookie_Item_Remove_Cookie_Button_Tooltip {
            get {
                return ResourceManager.GetString("Dialog_Login_Using_Cookies_Cookie_Item_Remove_Cookie_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Dialog_Login_Using_Cookies_Cookie_Item_Value_Field_Hint {
            get {
                return ResourceManager.GetString("Dialog_Login_Using_Cookies_Cookie_Item_Value_Field_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Dialog_Request_Challenge_Close_Dialog_Button {
            get {
                return ResourceManager.GetString("Dialog_Request_Challenge_Close_Dialog_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Dialog_Request_Challenge_Copy_Code_Button {
            get {
                return ResourceManager.GetString("Dialog_Request_Challenge_Copy_Code_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter this code in the client to finish pairing.
        /// </summary>
        internal static string Dialog_Request_Challenge_Enter_Code_In_Client {
            get {
                return ResourceManager.GetString("Dialog_Request_Challenge_Enter_Code_In_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Prompt.
        /// </summary>
        internal static string Dialog_Request_Challenge_Identity_Prompt_Title {
            get {
                return ResourceManager.GetString("Dialog_Request_Challenge_Identity_Prompt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request come from client.
        /// </summary>
        internal static string Dialog_Request_Challenge_Request_From_Client {
            get {
                return ResourceManager.GetString("Dialog_Request_Challenge_Request_From_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLY enter this code when the request COMES FROM the client you TRUST.
        /// </summary>
        internal static string Dialog_Request_Challenge_Security_Warning {
            get {
                return ResourceManager.GetString("Dialog_Request_Challenge_Security_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I know.
        /// </summary>
        internal static string Dialog_Rpc_Server_Port_Changed_Due_To_Bind_Error_Close_Dialog_Button_Text {
            get {
                return ResourceManager.GetString("Dialog_Rpc_Server_Port_Changed_Due_To_Bind_Error_Close_Dialog_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Port.
        /// </summary>
        internal static string Dialog_Rpc_Server_Port_Changed_Due_To_Bind_Error_Current_Port {
            get {
                return ResourceManager.GetString("Dialog_Rpc_Server_Port_Changed_Due_To_Bind_Error_Current_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPC Server failed to start with configured port, it may cause by the port is in use.
        ///Please notice that you need to re-pair with the app, or you can change port back after solve the problem..
        /// </summary>
        internal static string Dialog_Rpc_Server_Port_Changed_Due_To_Bind_Error_Description {
            get {
                return ResourceManager.GetString("Dialog_Rpc_Server_Port_Changed_Due_To_Bind_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPC Server port change due to bind error.
        /// </summary>
        internal static string Dialog_Rpc_Server_Port_Changed_Due_To_Bind_Error_Title {
            get {
                return ResourceManager.GetString("Dialog_Rpc_Server_Port_Changed_Due_To_Bind_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings Port.
        /// </summary>
        internal static string Dialog_Rpc_Server_Port_Changed_Due_To_Bind_Error_User_Settings_Port {
            get {
                return ResourceManager.GetString("Dialog_Rpc_Server_Port_Changed_Due_To_Bind_Error_User_Settings_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are uncompleted publish tasks.
        ///Are you really sure you want to shutdown the app?.
        /// </summary>
        internal static string Dialog_Shutdown_Ask_User_To_Confirm_Shutdown_With_Uncompleted_Tasks {
            get {
                return ResourceManager.GetString("Dialog_Shutdown_Ask_User_To_Confirm_Shutdown_With_Uncompleted_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Dialog_Shutdown_Cancel_Shutdown_With_Uncompleted_Tasks {
            get {
                return ResourceManager.GetString("Dialog_Shutdown_Cancel_Shutdown_With_Uncompleted_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes! I want to shutdown with uncompleted tasks!.
        /// </summary>
        internal static string Dialog_Shutdown_Confirm_Confirm_Shutdown_With_Uncompleted_Tasks {
            get {
                return ResourceManager.GetString("Dialog_Shutdown_Confirm_Confirm_Shutdown_With_Uncompleted_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Dialog_Update_Available_Cancel_Button_Text {
            get {
                return ResourceManager.GetString("Dialog_Update_Available_Cancel_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Dialog_Update_Available_Download_Update_Button_Text {
            get {
                return ResourceManager.GetString("Dialog_Update_Available_Download_Update_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Update Available.
        /// </summary>
        internal static string Dialog_Update_Available_Headline {
            get {
                return ResourceManager.GetString("Dialog_Update_Available_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Update.
        /// </summary>
        internal static string Dialog_Update_Available_Install_Update_Button_Text {
            get {
                return ResourceManager.GetString("Dialog_Update_Available_Install_Update_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this version.
        /// </summary>
        internal static string Dialog_Update_Available_Skip_Version_Button_Text {
            get {
                return ResourceManager.GetString("Dialog_Update_Available_Skip_Version_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released at {0}.
        /// </summary>
        internal static string Dialog_Update_Available_Subtitle_Release_Date_Template {
            get {
                return ResourceManager.GetString("Dialog_Update_Available_Subtitle_Release_Date_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must clear all uncompleted publish tasks before install update..
        /// </summary>
        internal static string Dialog_Update_Available_Uncompleted_Tasks_Exist_Warning {
            get {
                return ResourceManager.GetString("Dialog_Update_Available_Uncompleted_Tasks_Exist_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View on Browser.
        /// </summary>
        internal static string Dialog_Update_Available_View_On_Browser_Button_Text {
            get {
                return ResourceManager.GetString("Dialog_Update_Available_View_On_Browser_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        internal static string In_App_Notifications_New_Version_Available_Dismiss_Button_Tooltip {
            get {
                return ResourceManager.GetString("In_App_Notifications_New_Version_Available_Dismiss_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version v{0} is available!.
        /// </summary>
        internal static string In_App_Notifications_New_Version_Available_Title {
            get {
                return ResourceManager.GetString("In_App_Notifications_New_Version_Available_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string In_App_Notifications_New_Version_Available_View_Button_Text {
            get {
                return ResourceManager.GetString("In_App_Notifications_New_Version_Available_View_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string Internal_ClutureInfoCode_Use_For_Detect_System_Lanuage_Only__Modify_AppLocalizationService_To_Add_Lanauge_Option {
            get {
                return ResourceManager.GetString(("Internal_ClutureInfoCode_Use_For_Detect_System_Lanuage_Only__Modify_AppLocalizati" +
                        "onService_To_Add_Lanauge_Option"), resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old: {0} New: {1}.
        /// </summary>
        internal static string Notifications_Public_IP_Changed_Body_Template {
            get {
                return ResourceManager.GetString("Notifications_Public_IP_Changed_Body_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public IP Changed.
        /// </summary>
        internal static string Notifications_Public_IP_Changed_Title {
            get {
                return ResourceManager.GetString("Notifications_Public_IP_Changed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a test notification.
        /// </summary>
        internal static string Notifications_Settings_Test_Notification_Body {
            get {
                return ResourceManager.GetString("Notifications_Settings_Test_Notification_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Notification.
        /// </summary>
        internal static string Notifications_Settings_Test_Notification_Title {
            get {
                return ResourceManager.GetString("Notifications_Settings_Test_Notification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish {0} &quot;{1}&quot; Failed.
        /// </summary>
        internal static string Notifications_Task_Failed_Title_Template {
            get {
                return ResourceManager.GetString("Notifications_Task_Failed_Title_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Pages_Bootstrap_Loading_Text {
            get {
                return ResourceManager.GetString("Pages_Bootstrap_Loading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login.
        /// </summary>
        internal static string Pages_Add_Account_Alert_Login_Failed_Title {
            get {
                return ResourceManager.GetString("Pages_Add_Account_Alert_Login_Failed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Pages_Add_Account_Login_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Add_Account_Login_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login using cookies.
        /// </summary>
        internal static string Pages_Add_Account_Login_Using_Cookies_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Add_Account_Login_Using_Cookies_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify your code.
        /// </summary>
        internal static string Pages_Add_Account_Otp_Dialog_Alert_Failed_To_Verify_Code {
            get {
                return ResourceManager.GetString("Pages_Add_Account_Otp_Dialog_Alert_Failed_To_Verify_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Pages_Add_Account_Otp_Dialog_Code_Field_PlaceholderText {
            get {
                return ResourceManager.GetString("Pages_Add_Account_Otp_Dialog_Code_Field_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email for code.
        /// </summary>
        internal static string Pages_Add_Account_Otp_Dialog_Require_EmailOtp {
            get {
                return ResourceManager.GetString("Pages_Add_Account_Otp_Dialog_Require_EmailOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your TOTP App for code.
        /// </summary>
        internal static string Pages_Add_Account_Otp_Dialog_Require_Totp {
            get {
                return ResourceManager.GetString("Pages_Add_Account_Otp_Dialog_Require_Totp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Password Required.
        /// </summary>
        internal static string Pages_Add_Account_Otp_Dialog_Title {
            get {
                return ResourceManager.GetString("Pages_Add_Account_Otp_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Pages_Add_Account_Password_Field_Label {
            get {
                return ResourceManager.GetString("Pages_Add_Account_Password_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your.
        /// </summary>
        internal static string Pages_Add_Account_Title_Headline1 {
            get {
                return ResourceManager.GetString("Pages_Add_Account_Title_Headline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRChat Account.
        /// </summary>
        internal static string Pages_Add_Account_Title_Headline2_Bold {
            get {
                return ResourceManager.GetString("Pages_Add_Account_Title_Headline2_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username/Email.
        /// </summary>
        internal static string Pages_Add_Account_Username_Or_Email_Field_Label {
            get {
                return ResourceManager.GetString("Pages_Add_Account_Username_Or_Email_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please link your Pico, Oculus, Steam, or Viveport account to your VRChat Account follow this article in the below:.
        /// </summary>
        internal static string Pages_Add_Account_Using_No_VRChat_Account_Tip_Description {
            get {
                return ResourceManager.GetString("Pages_Add_Account_Using_No_VRChat_Account_Tip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using an Pico, Oculus, Steam, or Viveport account?.
        /// </summary>
        internal static string Pages_Add_Account_Using_No_VRChat_Account_Tip_Title {
            get {
                return ResourceManager.GetString("Pages_Add_Account_Using_No_VRChat_Account_Tip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Pages_Guide_Connect_Unity_To_App_Copy_Host_URL_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Guide_Connect_Unity_To_App_Copy_Host_URL_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish setup by.
        /// </summary>
        internal static string Pages_Guide_Connect_Unity_To_App_Headline1_Light {
            get {
                return ResourceManager.GetString("Pages_Guide_Connect_Unity_To_App_Headline1_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Unity to App.
        /// </summary>
        internal static string Pages_Guide_Connect_Unity_To_App_Headline2_Bold {
            get {
                return ResourceManager.GetString("Pages_Guide_Connect_Unity_To_App_Headline2_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host URL.
        /// </summary>
        internal static string Pages_Guide_Connect_Unity_To_App_Host_URL_Field_Hint {
            get {
                return ResourceManager.GetString("Pages_Guide_Connect_Unity_To_App_Host_URL_Field_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Pages_Guide_Connect_Unity_To_App_Skip_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Guide_Connect_Unity_To_App_Skip_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to App.
        /// </summary>
        internal static string Pages_Guide_Connect_Unity_To_App_Step_2_Connect_To_App_Title {
            get {
                return ResourceManager.GetString("Pages_Guide_Connect_Unity_To_App_Step_2_Connect_To_App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter following host address in Connect Settings in Unity, then press Connect..
        /// </summary>
        internal static string Pages_Guide_Connect_Unity_To_App_Step_2_Description {
            get {
                return ResourceManager.GetString("Pages_Guide_Connect_Unity_To_App_Step_2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish setup by.
        /// </summary>
        internal static string Pages_Guide_Open_Connect_Settings_In_Unity_Headline1_Light {
            get {
                return ResourceManager.GetString("Pages_Guide_Open_Connect_Settings_In_Unity_Headline1_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Unity to App.
        /// </summary>
        internal static string Pages_Guide_Open_Connect_Settings_In_Unity_Headline2_Bold {
            get {
                return ResourceManager.GetString("Pages_Guide_Open_Connect_Settings_In_Unity_Headline2_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Pages_Guide_Open_Connect_Settings_In_Unity_Next_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Guide_Open_Connect_Settings_In_Unity_Next_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Pages_Guide_Open_Connect_Settings_In_Unity_Skip_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Guide_Open_Connect_Settings_In_Unity_Skip_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tools &gt; VRChat Content Publisher Connect &gt; Settings to open Connect Settings.
        /// </summary>
        internal static string Pages_Guide_Open_Connect_Settings_In_Unity_Step_1_Description {
            get {
                return ResourceManager.GetString("Pages_Guide_Open_Connect_Settings_In_Unity_Step_1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Connect Settings.
        /// </summary>
        internal static string Pages_Guide_Open_Connect_Settings_In_Unity_Step_1_Open_Connect_Settings_Title {
            get {
                return ResourceManager.GetString("Pages_Guide_Open_Connect_Settings_In_Unity_Step_1_Open_Connect_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Connect Unity to App.
        /// </summary>
        internal static string Pages_Guide_Setup_Unity_Headline1_Light {
            get {
                return ResourceManager.GetString("Pages_Guide_Setup_Unity_Headline1_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Connect Package.
        /// </summary>
        internal static string Pages_Guide_Setup_Unity_Headline2_Bold {
            get {
                return ResourceManager.GetString("Pages_Guide_Setup_Unity_Headline2_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Pages_Guide_Setup_Unity_Next_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Guide_Setup_Unity_Next_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Pages_Guide_Setup_Unity_Skip_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Guide_Setup_Unity_Skip_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to the package manager.
        /// </summary>
        internal static string Pages_Guide_Setup_Unity_Step_1_Add_To_Package_Manager_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Guide_Setup_Unity_Step_1_Add_To_Package_Manager_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add VPM Repository.
        /// </summary>
        internal static string Pages_Guide_Setup_Unity_Step_1_Add_VPM_Repository_Title {
            get {
                return ResourceManager.GetString("Pages_Guide_Setup_Unity_Step_1_Add_VPM_Repository_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Pages_Guide_Setup_Unity_Step_1_Copy_Repository_URL_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Guide_Setup_Unity_Step_1_Copy_Repository_URL_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPM Repository URL.
        /// </summary>
        internal static string Pages_Guide_Setup_Unity_Step_1_VPM_Repository_URL_Field_Hint {
            get {
                return ResourceManager.GetString("Pages_Guide_Setup_Unity_Step_1_VPM_Repository_URL_Field_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Worlds Project.
        /// </summary>
        internal static string Pages_Guide_Setup_Unity_Step_2_For_Avatars_Project_Caption {
            get {
                return ResourceManager.GetString("Pages_Guide_Setup_Unity_Step_2_For_Avatars_Project_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are using Continuous Avatar Uploader.
        /// </summary>
        internal static string Pages_Guide_Setup_Unity_Step_2_For_Project_With_CAU_Caption {
            get {
                return ResourceManager.GetString("Pages_Guide_Setup_Unity_Step_2_For_Project_With_CAU_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Worlds Project.
        /// </summary>
        internal static string Pages_Guide_Setup_Unity_Step_2_For_Worlds_Project_Caption {
            get {
                return ResourceManager.GetString("Pages_Guide_Setup_Unity_Step_2_For_Worlds_Project_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Connect Package.
        /// </summary>
        internal static string Pages_Guide_Setup_Unity_Step_2_Install_Connect_Package_Title {
            get {
                return ResourceManager.GetString("Pages_Guide_Setup_Unity_Step_2_Install_Connect_Package_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.1.
        /// </summary>
        internal static string Pages_Guide_Shared_Steps_Step_1_Title {
            get {
                return ResourceManager.GetString("Pages_Guide_Shared_Steps_Step_1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.2.
        /// </summary>
        internal static string Pages_Guide_Shared_Steps_Step_2_Title {
            get {
                return ResourceManager.GetString("Pages_Guide_Shared_Steps_Step_2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A More Efficient Way.
        /// </summary>
        internal static string Pages_Guide_Welcome_Headline1_Bold {
            get {
                return ResourceManager.GetString("Pages_Guide_Welcome_Headline1_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to publish your VRChat contents.
        /// </summary>
        internal static string Pages_Guide_Welcome_Headline2_Light {
            get {
                return ResourceManager.GetString("Pages_Guide_Welcome_Headline2_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Pages_Guide_Welcome_Next_Page_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Guide_Welcome_Next_Page_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just take me to the Home page!.
        /// </summary>
        internal static string Pages_Guide_Welcome_Skip_To_Home_Page_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Guide_Welcome_Skip_To_Home_Page_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Borderless Window.
        /// </summary>
        internal static string Pages_Home_App_Bar_Toggle_Borderless_Window_Button_Tooltip {
            get {
                return ResourceManager.GetString("Pages_Home_App_Bar_Toggle_Borderless_Window_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless Window: Toggle prevent window hide ,
        ///Normal Window: Toggle window on top..
        /// </summary>
        internal static string Pages_Home_App_Bar_Toggle_Window_Pin_Button_Tooltip {
            get {
                return ResourceManager.GetString("Pages_Home_App_Bar_Toggle_Window_Pin_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Pages_Navigation_Go_Back_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Navigation_Go_Back_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgement.
        /// </summary>
        internal static string Pages_Settings_About_Acknowledgement_Title {
            get {
                return ResourceManager.GetString("Pages_Settings_About_Acknowledgement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified to meet VRChat Content Publisher requirements.
        /// </summary>
        internal static string Pages_Settings_About_AssetsTools_Modify_To_Meet_VCP_Requirements {
            get {
                return ResourceManager.GetString("Pages_Settings_About_AssetsTools_Modify_To_Meet_VCP_Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity AssetBundle Processing Powered by.
        /// </summary>
        internal static string Pages_Settings_About_AssetsTools_Unity_AssetBundle_Processing_Powered_By {
            get {
                return ResourceManager.GetString("Pages_Settings_About_AssetsTools_Unity_AssetBundle_Processing_Powered_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build at.
        /// </summary>
        internal static string Pages_Settings_About_Build_At {
            get {
                return ResourceManager.GetString("Pages_Settings_About_Build_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Commit SHA.
        /// </summary>
        internal static string Pages_Settings_About_Build_Commit {
            get {
                return ResourceManager.GetString("Pages_Settings_About_Build_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please consider support development by.
        /// </summary>
        internal static string Pages_Settings_About_Consider_Support_By {
            get {
                return ResourceManager.GetString("Pages_Settings_About_Consider_Support_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribute.
        /// </summary>
        internal static string Pages_Settings_About_Consider_Support_By_Content_Contribute {
            get {
                return ResourceManager.GetString("Pages_Settings_About_Consider_Support_By_Content_Contribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string Pages_Settings_About_Consider_Support_By_Content_Donate {
            get {
                return ResourceManager.GetString("Pages_Settings_About_Consider_Support_By_Content_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string Pages_Settings_About_Consider_Support_By_Content_Feedback {
            get {
                return ResourceManager.GetString("Pages_Settings_About_Consider_Support_By_Content_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRChat Content Publisher on Github.
        /// </summary>
        internal static string Pages_Settings_About_Gitub_Link_Text {
            get {
                return ResourceManager.GetString("Pages_Settings_About_Gitub_Link_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A More Efficient Way to publish your VRChat Contents.
        /// </summary>
        internal static string Pages_Settings_About_Slogan {
            get {
                return ResourceManager.GetString("Pages_Settings_About_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks to our early adopters.
        /// </summary>
        internal static string Pages_Settings_About_Special_Thanks_To_Our_Early_Adopters {
            get {
                return ResourceManager.GetString("Pages_Settings_About_Special_Thanks_To_Our_Early_Adopters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to those Open source software.
        /// </summary>
        internal static string Pages_Settings_About_Thanks_To_Those_Open_Soure_Software {
            get {
                return ResourceManager.GetString("Pages_Settings_About_Thanks_To_Those_Open_Soure_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Pages_Settings_About_Title {
            get {
                return ResourceManager.GetString("Pages_Settings_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRChat API documentation provided by.
        /// </summary>
        internal static string Pages_Settings_About_VRChat_API_Documentation_Provided_By {
            get {
                return ResourceManager.GetString("Pages_Settings_About_VRChat_API_Documentation_Provided_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot remove a session that have uncompleted tasks..
        /// </summary>
        internal static string Pages_Settings_Accounts_Account_Item_Remove_Button_Cannot_Remove_Account_Has_Uncompleted_Tasks_Tooltip {
            get {
                return ResourceManager.GetString(("Pages_Settings_Accounts_Account_Item_Remove_Button_Cannot_Remove_Account_Has_Unco" +
                        "mpleted_Tasks_Tooltip"), resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this account.
        /// </summary>
        internal static string Pages_Settings_Accounts_Account_Item_Remove_Button_Tooltip {
            get {
                return ResourceManager.GetString("Pages_Settings_Accounts_Account_Item_Remove_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair this account.
        /// </summary>
        internal static string Pages_Settings_Accounts_Account_Item_Repair_Button_Tooltip {
            get {
                return ResourceManager.GetString("Pages_Settings_Accounts_Account_Item_Repair_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is already set as default show on Tasks page..
        /// </summary>
        internal static string Pages_Settings_Accounts_Account_Item_Set_Default_Already_Set_Button_Tooltip {
            get {
                return ResourceManager.GetString("Pages_Settings_Accounts_Account_Item_Set_Default_Already_Set_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this account as default show on Tasks page..
        /// </summary>
        internal static string Pages_Settings_Accounts_Account_Item_Set_Default_Button_Tooltip {
            get {
                return ResourceManager.GetString("Pages_Settings_Accounts_Account_Item_Set_Default_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Account.
        /// </summary>
        internal static string Pages_Settings_Accounts_Add_New_Account {
            get {
                return ResourceManager.GetString("Pages_Settings_Accounts_Add_New_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string Pages_Settings_Accounts_Title {
            get {
                return ResourceManager.GetString("Pages_Settings_Accounts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Language.
        /// </summary>
        internal static string Pages_Settings_Appearance_App_Language {
            get {
                return ResourceManager.GetString("Pages_Settings_Appearance_App_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest first.
        /// </summary>
        internal static string Pages_Settings_Appearance_How_Tasks_Order_In_Tasks_Page_Selector_Latest_First {
            get {
                return ResourceManager.GetString("Pages_Settings_Appearance_How_Tasks_Order_In_Tasks_Page_Selector_Latest_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest first.
        /// </summary>
        internal static string Pages_Settings_Appearance_How_Tasks_Order_In_Tasks_Page_Selector_Oldest_First {
            get {
                return ResourceManager.GetString("Pages_Settings_Appearance_How_Tasks_Order_In_Tasks_Page_Selector_Oldest_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How tasks order in Tasks page.
        /// </summary>
        internal static string Pages_Settings_Appearance_How_Tasks_Order_In_Tasks_Page_Selector_Title {
            get {
                return ResourceManager.GetString("Pages_Settings_Appearance_How_Tasks_Order_In_Tasks_Page_Selector_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow system settings.
        /// </summary>
        internal static string Pages_Settings_Appearance_Language_Selector_Follow_System {
            get {
                return ResourceManager.GetString("Pages_Settings_Appearance_Language_Selector_Follow_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance and Language.
        /// </summary>
        internal static string Pages_Settings_Appearance_Title {
            get {
                return ResourceManager.GetString("Pages_Settings_Appearance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Borderless Window.
        /// </summary>
        internal static string Pages_Settings_Appearance_Use_Borderless_Window {
            get {
                return ResourceManager.GetString("Pages_Settings_Appearance_Use_Borderless_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use RGB Cycling Background App Bar.
        /// </summary>
        internal static string Pages_Settings_Appearance_Use_RGB_Cycling_Background_App_Bar {
            get {
                return ResourceManager.GetString("Pages_Settings_Appearance_Use_RGB_Cycling_Background_App_Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must re-pair with the app after changing the port..
        /// </summary>
        internal static string Pages_Settings_Connect_Alert_Change_Port_Require_Reconnect_Description {
            get {
                return ResourceManager.GetString("Pages_Settings_Connect_Alert_Change_Port_Require_Reconnect_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the port requires re-pairing.
        /// </summary>
        internal static string Pages_Settings_Connect_Alert_Change_Port_Require_Reconnect_Title {
            get {
                return ResourceManager.GetString("Pages_Settings_Connect_Alert_Change_Port_Require_Reconnect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Pages_Settings_Connect_Apply_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Settings_Connect_Apply_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name are require..
        /// </summary>
        internal static string Pages_Settings_Connect_Apply_Error_Empty_Server_Name {
            get {
                return ResourceManager.GetString("Pages_Settings_Connect_Apply_Error_Empty_Server_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port must be between {0} to {1}..
        /// </summary>
        internal static string Pages_Settings_Connect_Apply_Error_Port_Out_Of_Range {
            get {
                return ResourceManager.GetString("Pages_Settings_Connect_Apply_Error_Port_Out_Of_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to apply RPC Serer settings due to unknown error..
        /// </summary>
        internal static string Pages_Settings_Connect_Apply_Error_Unknown_Error {
            get {
                return ResourceManager.GetString("Pages_Settings_Connect_Apply_Error_Unknown_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name.
        /// </summary>
        internal static string Pages_Settings_Connect_Server_Name_Field_Label {
            get {
                return ResourceManager.GetString("Pages_Settings_Connect_Server_Name_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g Greatest Chiffon.
        /// </summary>
        internal static string Pages_Settings_Connect_Server_Name_Field_PlaceholderText {
            get {
                return ResourceManager.GetString("Pages_Settings_Connect_Server_Name_Field_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Port.
        /// </summary>
        internal static string Pages_Settings_Connect_Server_Port_Field_Label {
            get {
                return ResourceManager.GetString("Pages_Settings_Connect_Server_Port_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Port to Default.
        /// </summary>
        internal static string Pages_Settings_Connect_Server_Port_Reset_To_Default_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Settings_Connect_Server_Port_Reset_To_Default_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPC Server.
        /// </summary>
        internal static string Pages_Settings_Connect_Title {
            get {
                return ResourceManager.GetString("Pages_Settings_Connect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed under GPL-3.0 license.
        /// </summary>
        internal static string Pages_Settings_Copyright {
            get {
                return ResourceManager.GetString("Pages_Settings_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        internal static string Pages_Settings_Debug_Encrypted_IP_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Settings_Debug_Encrypted_IP_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter encrypted IP in the logs here.
        /// </summary>
        internal static string Pages_Settings_Debug_Encrypted_IP_Field_Label {
            get {
                return ResourceManager.GetString("Pages_Settings_Debug_Encrypted_IP_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Logs Folder.
        /// </summary>
        internal static string Pages_Settings_Debug_Open_Logs_Folder_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Settings_Debug_Open_Logs_Folder_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Network Diagnostics Window.
        /// </summary>
        internal static string Pages_Settings_Debug_Open_Network_Diagnostics_Window {
            get {
                return ResourceManager.GetString("Pages_Settings_Debug_Open_Network_Diagnostics_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Pages_Settings_Debug_Title {
            get {
                return ResourceManager.GetString("Pages_Settings_Debug_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom HTTP Proxy URI.
        /// </summary>
        internal static string Pages_Settings_Http_Proxy_Custom_Proxy_URI_Field {
            get {
                return ResourceManager.GetString("Pages_Settings_Http_Proxy_Custom_Proxy_URI_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Proxy URI must be a http or https URI..
        /// </summary>
        internal static string Pages_Settings_Http_Proxy_Custom_Proxy_URI_Vlidation_Failed_Message {
            get {
                return ResourceManager.GetString("Pages_Settings_Http_Proxy_Custom_Proxy_URI_Vlidation_Failed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Proxy.
        /// </summary>
        internal static string Pages_Settings_Http_Proxy_Proxy_Mode_Selector_Custom_Porxy {
            get {
                return ResourceManager.GetString("Pages_Settings_Http_Proxy_Proxy_Mode_Selector_Custom_Porxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow System Settings.
        /// </summary>
        internal static string Pages_Settings_Http_Proxy_Proxy_Mode_Selector_Follow_System_Settings {
            get {
                return ResourceManager.GetString("Pages_Settings_Http_Proxy_Proxy_Mode_Selector_Follow_System_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Mode.
        /// </summary>
        internal static string Pages_Settings_Http_Proxy_Proxy_Mode_Selector_Label {
            get {
                return ResourceManager.GetString("Pages_Settings_Http_Proxy_Proxy_Mode_Selector_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Proxy.
        /// </summary>
        internal static string Pages_Settings_Http_Proxy_Proxy_Mode_Selector_No_Proxy {
            get {
                return ResourceManager.GetString("Pages_Settings_Http_Proxy_Proxy_Mode_Selector_No_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Proxy.
        /// </summary>
        internal static string Pages_Settings_Http_Proxy_Title {
            get {
                return ResourceManager.GetString("Pages_Settings_Http_Proxy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Notifications.
        /// </summary>
        internal static string Pages_Settings_Notification_Enable_Notifications_Toggle_Label {
            get {
                return ResourceManager.GetString("Pages_Settings_Notification_Enable_Notifications_Toggle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Session Expired on Startup.
        /// </summary>
        internal static string Pages_Settings_Notification_Send_Notifications_When_Account_Session_Expired_On_Startup {
            get {
                return ResourceManager.GetString(("Pages_Settings_Notification_Send_Notifications_When_Account_Session_Expired_On_St" +
                        "artup"), resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public IP Changed.
        /// </summary>
        internal static string Pages_Settings_Notification_Send_Notifications_When_Public_IP_Changed {
            get {
                return ResourceManager.GetString("Pages_Settings_Notification_Send_Notifications_When_Public_IP_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Task Failed.
        /// </summary>
        internal static string Pages_Settings_Notification_Send_Notifications_When_Publish_Task_Failed {
            get {
                return ResourceManager.GetString("Pages_Settings_Notification_Send_Notifications_When_Publish_Task_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send notifications when.
        /// </summary>
        internal static string Pages_Settings_Notification_Send_Notifications_When_Title {
            get {
                return ResourceManager.GetString("Pages_Settings_Notification_Send_Notifications_When_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Test Notification.
        /// </summary>
        internal static string Pages_Settings_Notification_Send_Test_Notification {
            get {
                return ResourceManager.GetString("Pages_Settings_Notification_Send_Test_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Pages_Settings_Notification_Title {
            get {
                return ResourceManager.GetString("Pages_Settings_Notification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client session will expire at {0}.
        /// </summary>
        internal static string Pages_Settings_PairedClients_Client_Item_Expired_At_Text_Template {
            get {
                return ResourceManager.GetString("Pages_Settings_PairedClients_Client_Item_Expired_At_Text_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke Client Session.
        /// </summary>
        internal static string Pages_Settings_PairedClients_Client_Item_Revoke_Client_Button_Tooltip {
            get {
                return ResourceManager.GetString("Pages_Settings_PairedClients_Client_Item_Revoke_Client_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paired Clients.
        /// </summary>
        internal static string Pages_Settings_PairedClients_Title {
            get {
                return ResourceManager.GetString("Pages_Settings_PairedClients_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At start and background.
        /// </summary>
        internal static string Pages_Settings_Software_Update_Auto_Check_Update_Mode_Selector_At_Start_And_Background {
            get {
                return ResourceManager.GetString(("Pages_Settings_Software_Update_Auto_Check_Update_Mode_Selector_At_Start_And_Backg" +
                        "round"), resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string Pages_Settings_Software_Update_Auto_Check_Update_Mode_Selector_Manual {
            get {
                return ResourceManager.GetString("Pages_Settings_Software_Update_Auto_Check_Update_Mode_Selector_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only at start.
        /// </summary>
        internal static string Pages_Settings_Software_Update_Auto_Check_Update_Mode_Selector_Only_At_Start {
            get {
                return ResourceManager.GetString("Pages_Settings_Software_Update_Auto_Check_Update_Mode_Selector_Only_At_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Check Update Mode.
        /// </summary>
        internal static string Pages_Settings_Software_Update_Auto_Check_Update_Mode_Selector_Title {
            get {
                return ResourceManager.GetString("Pages_Settings_Software_Update_Auto_Check_Update_Mode_Selector_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check for update: {0}.
        /// </summary>
        internal static string Pages_Settings_Software_Update_Check_For_Status_Failed_To_Check_Update_Template {
            get {
                return ResourceManager.GetString("Pages_Settings_Software_Update_Check_For_Status_Failed_To_Check_Update_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already up-to-dated.
        /// </summary>
        internal static string Pages_Settings_Software_Update_Check_For_Status_Up_To_Dated {
            get {
                return ResourceManager.GetString("Pages_Settings_Software_Update_Check_For_Status_Up_To_Dated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        internal static string Pages_Settings_Software_Update_Check_For_Update_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Settings_Software_Update_Check_For_Update_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear version skip and Check for update.
        /// </summary>
        internal static string Pages_Settings_Software_Update_Check_For_Update_Clear_Version_Skip_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Settings_Software_Update_Check_For_Update_Clear_Version_Skip_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download update at background.
        /// </summary>
        internal static string Pages_Settings_Software_Update_Download_Update_At_Background_Toggle_Label {
            get {
                return ResourceManager.GetString("Pages_Settings_Software_Update_Download_Update_At_Background_Toggle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive pre-release update.
        /// </summary>
        internal static string Pages_Settings_Software_Update_Receive_Pre_Release_Update_Toggle_Label {
            get {
                return ResourceManager.GetString("Pages_Settings_Software_Update_Receive_Pre_Release_Update_Toggle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Update.
        /// </summary>
        internal static string Pages_Settings_Software_Update_Title {
            get {
                return ResourceManager.GetString("Pages_Settings_Software_Update_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Pages_Settings_Title {
            get {
                return ResourceManager.GetString("Pages_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Action_Menu_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Action_Menu_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Removable Tasks.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Action_Menu_Remove_All_Removable_Tasks {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Action_Menu_Remove_All_Removable_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Cancelled Tasks.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Action_Menu_Remove_Cancelled_Tasks {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Action_Menu_Remove_Cancelled_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Completed Tasks.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Action_Menu_Remove_Completed_Tasks {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Action_Menu_Remove_Completed_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Failed Tasks.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Action_Menu_Remove_Failed_Tasks {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Action_Menu_Remove_Failed_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Tasks.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Action_Menu_Retry_All_Tasks {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Action_Menu_Retry_All_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your VRChat account must have a trust rank of &quot;New User&quot; or higher to publish content.
        ///VRChat Content Publisher won&apos;t prevent you from publish content for this account, but it will likely fail.
        ///
        ///If you still saw this or still unable to publish content when you have meet the requirement.
        ///Please try using VRChat SDK to publish content, if fail, contact VRChat Support, if not, create a issues on github report this..
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Alert_Account_No_Content_Publish_Permission_Description {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Alert_Account_No_Content_Publish_Permission_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Alert_Account_No_Content_Publish_Permission_Learn_More_Button_Text {
            get {
                return ResourceManager.GetString(("Pages_Tasks_Account_Tab_Alert_Account_No_Content_Publish_Permission_Learn_More_Bu" +
                        "tton_Text"), resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account are not allowed to publish content.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Alert_Account_No_Content_Publish_Permission_Title {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Alert_Account_No_Content_Publish_Permission_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks in publish stage will be cancel and no retry allowed before account repaired..
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Alert_Session_Expired_Or_Invalid_Description {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Alert_Session_Expired_Or_Invalid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Alert_Session_Expired_Or_Invalid_Reapir_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Alert_Session_Expired_Or_Invalid_Reapir_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired or Invalid.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Alert_Session_Expired_Or_Invalid_Title {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Alert_Session_Expired_Or_Invalid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It may cause by network issue, public IP changed or session expired.
        ///Click Repair Account to re-try or login again..
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Initialize_Error_Description {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Initialize_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Account.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Initialize_Error_Repair_Account_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Initialize_Error_Repair_Account_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize this account.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Initialize_Error_Title {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Initialize_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks exist for this account.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Placeholder_No_Tasks_Exist {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Placeholder_No_Tasks_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Task_Item_Cancel_Task_Button_Tooltip {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Task_Item_Cancel_Task_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Task_Item_Debug_Button_Tooltip {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Task_Item_Debug_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Task_Item_Remove_Task_Button_Tooltip {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Task_Item_Remove_Task_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Task_Item_Retry_Task_Button_Tooltip {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Task_Item_Retry_Task_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at {0}.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Task_Item_Task_Created_At_Template {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Task_Item_Task_Created_At_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks Canceled.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Tasks_Count_Canceled_Tooltip {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Tasks_Count_Canceled_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks Completed.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Tasks_Count_Completed_Tooltip {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Tasks_Count_Completed_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks Failed.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Tasks_Count_Failed_Tooltip {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Tasks_Count_Failed_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks In Progress.
        /// </summary>
        internal static string Pages_Tasks_Account_Tab_Tasks_Count_In_Progress_Tooltip {
            get {
                return ResourceManager.GetString("Pages_Tasks_Account_Tab_Tasks_Count_In_Progress_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Public IP:.
        /// </summary>
        internal static string Pages_Tasks_Alert_Public_IP_Changed_Current_Public_IP_Text {
            get {
                return ResourceManager.GetString("Pages_Tasks_Alert_Public_IP_Changed_Current_Public_IP_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        internal static string Pages_Tasks_Alert_Public_IP_Changed_Dismiss_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Tasks_Alert_Public_IP_Changed_Dismiss_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Public IP:.
        /// </summary>
        internal static string Pages_Tasks_Alert_Public_IP_Changed_Last_Public_IP_Text {
            get {
                return ResourceManager.GetString("Pages_Tasks_Alert_Public_IP_Changed_Last_Public_IP_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your public IP address has changed since the last time you logged in. This may cause login issues. You may need to click Repair Account button to login again
        ///Tip: If you switch back to your last public IP, you can click Repair Account button without login again..
        /// </summary>
        internal static string Pages_Tasks_Alert_Public_IP_Changed_Message {
            get {
                return ResourceManager.GetString("Pages_Tasks_Alert_Public_IP_Changed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show IP.
        /// </summary>
        internal static string Pages_Tasks_Alert_Public_IP_Changed_Show_IP_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Tasks_Alert_Public_IP_Changed_Show_IP_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Pages_Tasks_No_VRChat_Account_Exist_Login_Button_Text {
            get {
                return ResourceManager.GetString("Pages_Tasks_No_VRChat_Account_Exist_Login_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t login any VRChat accounts.
        /// </summary>
        internal static string Pages_Tasks_No_VRChat_Account_Exist_Title {
            get {
                return ResourceManager.GetString("Pages_Tasks_No_VRChat_Account_Exist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Account.
        /// </summary>
        internal static string Pages_Tasks_Tabs_Add_New_Account_Button_Tooltip {
            get {
                return ResourceManager.GetString("Pages_Tasks_Tabs_Add_New_Account_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Pages_Tasks_Title {
            get {
                return ResourceManager.GetString("Pages_Tasks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Borderless Window.
        /// </summary>
        internal static string Tray_Menu_Borderless_Window_Toggle_Checked_Text {
            get {
                return ResourceManager.GetString("Tray_Menu_Borderless_Window_Toggle_Checked_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Borderless Window.
        /// </summary>
        internal static string Tray_Menu_Borderless_Window_Toggle_Unchecked_Text {
            get {
                return ResourceManager.GetString("Tray_Menu_Borderless_Window_Toggle_Unchecked_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Logs Folder.
        /// </summary>
        internal static string Tray_Menu_Open_Logs_Folder {
            get {
                return ResourceManager.GetString("Tray_Menu_Open_Logs_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin Window.
        /// </summary>
        internal static string Tray_Menu_Pinned_Window_Toggle_Checked_Text {
            get {
                return ResourceManager.GetString("Tray_Menu_Pinned_Window_Toggle_Checked_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Window.
        /// </summary>
        internal static string Tray_Menu_Pinned_Window_Toggle_Unchecked_Text {
            get {
                return ResourceManager.GetString("Tray_Menu_Pinned_Window_Toggle_Unchecked_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Window.
        /// </summary>
        internal static string Tray_Menu_Show_Main_Window {
            get {
                return ResourceManager.GetString("Tray_Menu_Show_Main_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Tray_Menu_Show_Shutdown_App {
            get {
                return ResourceManager.GetString("Tray_Menu_Show_Shutdown_App", resourceCulture);
            }
        }
    }
}
