name: Build
on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: git ref to build
        default: ${{ github.ref_name }}
  push:
    paths:
      - src/**
      - .github/workflows/build.yml
  pull_request:
    paths:
      - src/**
      - .github/workflows/build.yml

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: blacksmith-4vcpu-windows-2025
            rid: win-x64
            target-framework: net10.0-windows10.0.17763.0
          - os: blacksmith-4vcpu-ubuntu-2404
            rid: linux-x64
            target-framework: net10.0

    runs-on: ${{ matrix.os }}

    env:
      repo_dir: ${{ github.workspace }}/repo
      src_dir: ${{ github.workspace }}/repo/src
      output_dir: ${{ github.workspace }}/output

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}
          path: ${{ env.repo_dir }}
          submodules: recursive

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"
          cache: true
          cache-dependency-path: ${{ env.src_dir }}/App/VRChatContentPublisher.App/VRChatContentPublisher.App.csproj

      - name: Restore
        run: dotnet restore App/VRChatContentPublisher.App --locked-mode
        shell: bash
        working-directory: ${{ env.src_dir }}

      - name: Build
        env:
          RID: ${{ matrix.rid }}
          BUILD_OUTPUT_DIR: ${{ env.output_dir }}
          TARGET_FRAMEWORK: ${{ matrix.target-framework }}
        run: dotnet publish -c Release App/VRChatContentPublisher.App -r $RID -o $BUILD_OUTPUT_DIR -f $TARGET_FRAMEWORK --no-restore
        shell: bash
        working-directory: ${{ env.src_dir }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: vrchat-content-publisher-only-app-${{ matrix.rid }}
          path: |
            ${{ env.output_dir }}
            !${{ env.output_dir }}/**/*.pdb
            !${{ env.output_dir }}/**/*.dbg

      - name: Upload PDB
        uses: actions/upload-artifact@v7
        with:
          name: vrchat-content-publisher-only-app-${{ matrix.rid }}-pdb
          path: |
            ${{ env.output_dir }}/**/*.pdb
            ${{ env.output_dir }}/**/*.dbg

  build-crash-handler:
    strategy:
      matrix:
        include:
          - os: blacksmith-4vcpu-windows-2025
            rid: win-x64
          - os: blacksmith-4vcpu-ubuntu-2404
            rid: linux-x64

    runs-on: ${{ matrix.os }}

    env:
      repo_dir: ${{ github.workspace }}/repo
      src_dir: ${{ github.workspace }}/repo/src
      output_dir: ${{ github.workspace }}/output

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}
          path: ${{ env.repo_dir }}
          submodules: recursive

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"
          cache: true
          cache-dependency-path: ${{ env.src_dir }}/App/CrashHandler/VRChatContentPublisher.CrashHandler.App/VRChatContentPublisher.CrashHandler.App.csproj

      - name: Restore
        run: dotnet restore App/CrashHandler/VRChatContentPublisher.CrashHandler.App --locked-mode
        shell: bash
        working-directory: ${{ env.src_dir }}

      - name: Build
        env:
          RID: ${{ matrix.rid }}
          BUILD_OUTPUT_DIR: ${{ env.output_dir }}
        run: dotnet publish -c Release App/CrashHandler/VRChatContentPublisher.CrashHandler.App -r $RID -o $BUILD_OUTPUT_DIR --no-restore
        shell: bash
        working-directory: ${{ env.src_dir }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: vrchat-content-publisher-crash-handler-${{ matrix.rid }}
          path: |
            ${{ env.output_dir }}
            !${{ env.output_dir }}/**/*.pdb
            !${{ env.output_dir }}/**/*.dbg

      - name: Upload PDB
        uses: actions/upload-artifact@v7
        with:
          name: vrchat-content-publisher-crash-handler-${{ matrix.rid }}-pdb
          path: |
            ${{ env.output_dir }}/**/*.pdb
            ${{ env.output_dir }}/**/*.dbg

  merge-artifacts:
    strategy:
      matrix:
        include:
          - rid: win-x64
          - rid: linux-x64

    needs: [build, build-crash-handler]
    runs-on: ubuntu-latest

    env:
      artifact_dir: ${{ github.workspace }}/artifacts
      output_dir: ${{ github.workspace }}/output

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: vrchat-content-publisher-only-app-${{ matrix.rid }}
          path: ${{ env.artifact_dir }}

      - name: Download Crash Handler Artifacts
        uses: actions/download-artifact@v8
        with:
          name: vrchat-content-publisher-crash-handler-${{ matrix.rid }}
          path: ${{ env.artifact_dir }}/CrashHandler

      - name: Upload Merged Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: vrchat-content-publisher-app-${{ matrix.rid }}
          path: ${{ env.artifact_dir }}

  make-nsis-windows-installer:
    needs: merge-artifacts
    runs-on: blacksmith-2vcpu-windows-2025

    env:
      repo_dir: ${{ github.workspace }}/repo
      installer_working_dir: ${{ github.workspace }}/repo/distribution/windows-installer
      installer_script: installer.nsi
      installer_output_name: vrchat-content-publisher-installer.exe
      artifact_dir: ${{ github.workspace }}/artifacts
      executable_name: VRChatContentPublisher.App.exe
      installer_product_version: ""
      installer_file_version: ""

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: vrchat-content-publisher-app-win-x64
          path: ${{ env.artifact_dir }}

      - name: Get Version Info
        id: get-version-info
        shell: powershell
        working-directory: ${{ env.artifact_dir }}
        run: |
          "installer_product_version=" + (Get-Item ${{ env.executable_name }} | Select-Object -ExpandProperty VersionInfo | Select-Object -ExpandProperty ProductVersion) >> $Env:GITHUB_ENV
          "installer_file_version=" + (Get-Item ${{ env.executable_name }} | Select-Object -ExpandProperty VersionInfo | Select-Object -ExpandProperty FileVersion) >> $Env:GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}
          path: ${{ env.repo_dir }}

      - name: Install NSIS
        uses: repolevedavaj/install-nsis@a55ed92772254d1e51d880f85ce9b5719f907801
        with:
          nsis-version: 3.11

      - name: Create NSIS Installer
        shell: powershell
        working-directory: ${{ env.installer_working_dir }}
        env:
          INSTALLER_DISPLAY_VERSION: ${{ env.installer_product_version }}
          INSTALLER_OLD_CLASSIC_VERSION: ${{ env.installer_file_version }}
          INSTALLER_PATH_TO_BUNDLE: ${{ env.artifact_dir }}
        run: makensis ${{ env.installer_script }}

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v7
        with:
          name: vrchat-content-publisher-app-win-x64-installer
          path: ${{ env.installer_working_dir }}/${{ env.installer_output_name }}