name: Build
on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: git ref to build
        default: ${{ github.ref_name }}
      sentry-environment:
        type: string
        description: Environment name to use for Sentry
        default: snapshot
      use-production-sentry-dsn:
        type: boolean
        description: Whether to use production Sentry DSN
        default: false
  push:
    paths:
      - src/**
      - .github/workflows/build.yml
  pull_request:
    paths:
      - src/**
      - .github/workflows/build.yml

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
            target-framework: net10.0-windows10.0.17763.0
          - os: ubuntu-latest
            rid: linux-x64
            target-framework: net10.0

    runs-on: ${{ matrix.os }}

    env:
      repo_dir: ${{ github.workspace }}/repo
      src_dir: ${{ github.workspace }}/repo/src
      sentry_environment: ${{ case(inputs.sentry-environment != null && inputs.sentry-environment != '', inputs.sentry-environment, 'snapshot') }}
      output_dir: ${{ github.workspace }}/output

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}
          path: ${{ env.repo_dir }}
          submodules: recursive

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Build
        env:
          RID: ${{ matrix.rid }}
          BUILD_OUTPUT_DIR: ${{ env.output_dir }}
          TARGET_FRAMEWORK: ${{ matrix.target-framework }}
          SENTRY_DSN: ${{ case(inputs.use-production-sentry-dsn, secrets.SENTRY_DSN, secrets.SENTRY_DSN_DEBUG) }}
        run: dotnet publish -c Release App/VRChatContentPublisher.App -r $RID -o $BUILD_OUTPUT_DIR -f $TARGET_FRAMEWORK -p:SentryDsn=$SENTRY_DSN -p:SentryEnvironment=$sentry_environment
        shell: bash
        working-directory: ${{ env.src_dir }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: vrchat-content-publisher-only-app-${{ matrix.rid }}
          path: |
            ${{ env.output_dir }}
            !${{ env.output_dir }}/**/*.pdb
            !${{ env.output_dir }}/**/*.dbg

      - name: Upload PDB
        uses: actions/upload-artifact@v7
        with:
          name: pdb-app-${{ matrix.rid }}
          path: |
            ${{ env.output_dir }}/**/*.pdb
            ${{ env.output_dir }}/**/*.dbg

  build-crash-handler:
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          - os: ubuntu-latest
            rid: linux-x64

    runs-on: ${{ matrix.os }}

    env:
      repo_dir: ${{ github.workspace }}/repo
      src_dir: ${{ github.workspace }}/repo/src
      output_dir: ${{ github.workspace }}/output

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}
          path: ${{ env.repo_dir }}
          submodules: recursive

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Build
        env:
          RID: ${{ matrix.rid }}
          BUILD_OUTPUT_DIR: ${{ env.output_dir }}
        run: dotnet publish -c Release App/CrashHandler/VRChatContentPublisher.CrashHandler.App -r $RID -o $BUILD_OUTPUT_DIR
        shell: bash
        working-directory: ${{ env.src_dir }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: vrchat-content-publisher-crash-handler-${{ matrix.rid }}
          path: |
            ${{ env.output_dir }}
            !${{ env.output_dir }}/**/*.pdb
            !${{ env.output_dir }}/**/*.dbg

      - name: Upload PDB
        uses: actions/upload-artifact@v7
        with:
          name: pdb-crash-handler-${{ matrix.rid }}
          path: |
            ${{ env.output_dir }}/**/*.pdb
            ${{ env.output_dir }}/**/*.dbg

  merge-artifacts:
    strategy:
      matrix:
        include:
          - rid: win-x64
          - rid: linux-x64

    needs: [build, build-crash-handler]
    runs-on: ubuntu-latest

    env:
      artifact_dir: ${{ github.workspace }}/artifacts
      output_dir: ${{ github.workspace }}/output

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: vrchat-content-publisher-only-app-${{ matrix.rid }}
          path: ${{ env.artifact_dir }}

      - name: Download Crash Handler Artifacts
        uses: actions/download-artifact@v8
        with:
          name: vrchat-content-publisher-crash-handler-${{ matrix.rid }}
          path: ${{ env.artifact_dir }}/CrashHandler

      - name: Upload Merged Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: unpacked-portable-${{ matrix.rid }}
          path: ${{ env.artifact_dir }}

  make-windows-installer-inno:
    needs: merge-artifacts
    runs-on: windows-latest

    env:
      repo_dir: ${{ github.workspace }}/repo
      installer_script_path: ${{ github.workspace }}/repo/distribution/windows-installer-inno/installer.iss
      installer_output_dir: ${{ github.workspace }}/installer-output
      installer_output_base_name: vrchat-content-publisher-installer
      artifact_dir: ${{ github.workspace }}/artifacts
      executable_name: VRChatContentPublisher.App.exe
      installer_product_version: ""

    steps:
      - name: Install Inno Setup
        run: choco install innosetup -y
        shell: pwsh

      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: unpacked-portable-win-x64
          path: ${{ env.artifact_dir }}

      - name: Get Version Info
        id: get-version-info
        shell: powershell
        working-directory: ${{ env.artifact_dir }}
        run: |
          "installer_product_version=" + (Get-Item ${{ env.executable_name }} | Select-Object -ExpandProperty VersionInfo | Select-Object -ExpandProperty ProductVersion) >> $Env:GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}
          path: ${{ env.repo_dir }}

      - name: Build Installer
        run: iscc /O"${{ env.installer_output_dir }}" /F"${{ env.installer_output_base_name }}" /DMyAppVersion=${{ env.installer_product_version }} /DAppArtifactPath="${{ env.artifact_dir }}" ${{ env.installer_script_path }}
      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v7
        with:
          name: installer-win-x64
          path: ${{ env.installer_output_dir }}/${{ env.installer_output_base_name }}.exe
